### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by bpnoel01** [DSheirer/sdrtrunk#1125]
I'm using sdrtrunk v0.4.0
I am trying to setup a simulcast site here: [(https://www.radioreference.com/apps/db/?siteId=29239)]
I am not getting any audio at all.
Here are some screen shots:
![CMD](https://user-images.githubusercontent.com/38449883/146654120-2c6d0e3f-cc07-4068-bce5-b4e420e4f89c.jpg)
![Now Playing](https://user-images.githubusercontent.com/38449883/146654121-96aab61a-57bc-4af6-9825-03feea7c82fd.jpg)
![Tuner](https://user-images.githubusercontent.com/38449883/146654123-071ed2ac-16f1-4d8a-aaad-a0d6192b49f1.jpg)

I know there are a few open issues regarding my problem, but they have not helped to solve my issue. I am very new at this. Please let me know if you have any suggestions. Thank you.

**Comment by DSheirer** [comment]
Github issues are for documenting problems with the software, not for providing user support.

You can use the sdrtrunk email distro on google groups to submit user support requests like this: https://groups.google.com/g/sdrtrunk

If you look closely at the spectral display in your second and third screenshots, you can see that there is no radio signal being transmitted on the primary control frequency (773.63125).

You may have to add in the alternate control frequencies so that sdrtrunk will hop across the primary and alternate control frequencies until it finds the active control channel.

You may also have to adjust your tuner's PPM value to ensure that the signals in the spectral display align with the frequency readouts.

Closing this issue.  Please post any followup questions to the email user support group.  

cheers,
Denny
