### ISSUE TITLE
Update Version to 0.6.0 Beta 5

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#1720]
Updates version 0.6.0 Beta 5 for next release.

**Comment by yrless** [comment]
Hi...loaded 0.6.0 Beta 5. Everything loads correctly including JMBE library (1.0.9) but no P25 audio. Using HackRF One so sufficient bandwidth and nearest radio site about 1 mile away (-75 dBm rssi). Can see control channel and traffic channels in the channel view but no decoded audio. Audio is fine otherwise on conventional FM repeaters. Could this be a P25 system issue? I don't think this county system in encrypted (Morris County NJ). Thnx.

**Comment by yrless** [comment]
Thank you.
