### ISSUE TITLE
P25 Audio Recordings Limited to 10 seconds

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#387]
A user reports that recordings of P25 audio calls that exceed 10 seconds are being truncated at 10 seconds.

**Comment by ImagoTrigger** [comment]
I can confirm and reproduce every time an automated county fire dispatch is called because it has a slow synthesized speech cadence with tones, grid box, description, etc. the call length is always >10 seconds and >158KB in .wav data.

160980 bytes seems to be a hard limit in v4.  v3 does not exhibit this behavior.

**Comment by ImagoTrigger** [comment]
I've spent a good part of the day messing with this.  I can now get recordings up to 480948 bytes (again, give or take a few bytes I assume for INFO/RIFF stuff).  Attached are my changes, I don't know which one of the 3 made a difference, yet.  I'm hoping someone can figure it out besides me ;-)




[10sec_1.diff.txt](https://github.com/DSheirer/sdrtrunk/files/2454510/10sec_1.diff.txt)
[10sec_2.diff.txt](https://github.com/DSheirer/sdrtrunk/files/2454511/10sec_2.diff.txt)
[10sec_3.diff.txt](https://github.com/DSheirer/sdrtrunk/files/2454512/10sec_3.diff.txt)

**Comment by DSheirer** [comment]
Thanks for finding this!  It's the resizing of the audio queue that did it.  Actually, I think the issue is that the reusable audio packet queue is not decrementing the total buffer count correctly when it takes buffers out of the queue and that's causing the overflow mechanism to kick in.
