### ISSUE TITLE
Detect Duplicate Talkgroup Definitions or Range Overlaps

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#507]
Update alias list protocol-specific maps to detect when duplicate talkgroup identifiers exist for the same protocol.  Also check for talkgroup range overlaps.

Log these issues for now, but consider adding support for notiifications via the user interface

**Comment by davidmckenzie** [comment]
Range overlaps is a fun one... should there maybe be a third "layer" of alias matching instead? E.g. I have an alias for talkgroup '12345', an alias for '12340-12349', and an alias for '0-136000' (or whatever the max was).

The scenario would be if I knew 12345 was a particular channel of a particular agency that I wanted to have top priortiy, I knew that agency held talkgroups in that 10 digit range and I wanted them to have a medium priority, and I want to mute everything else.

So instead of worrying about overlapping ranges, you just match on the most specific one (smallest range).
