### ISSUE TITLE
Java 12

### ISSUE THREAD

**Issue by mtoadvine** [DSheirer/sdrtrunk#561]
Compiled using Java 12 (because it's the latest release from Oracle), but everything runs using Java 11 causing an Unsupported Class Error. This leads to loss of functionality when reading in the JMBE libraries. If JMBE libraries are not defined or called, there are no issues, but no P25 decoding either.

**Comment by DSheirer** [comment]
The latest (pre-compiled) release version is available on the Releases page: https://github.com/DSheirer/sdrtrunk/releases

If you really want to use Java 12, you'll have to download the Java 12 JDK and update the 'build.gradle' script with the path to the Java 12 JDK in order to have the build script bundle the output product with the Java 12 JRE.
