### ISSUE TITLE
CDS Squelch Tone Decoder

### ISSUE THREAD

**Issue by imagesafari** [DSheirer/sdrtrunk#80]
Looking for a way to record multiple analog conventional frequencies, ideally with squelch or CTCSS squelch. Could this be added?

**Comment by DSheirer** [comment]
Ticket #36 is a feature request for NBFM squelch.
 
I'll rename this feature request to CSCSS squelching.

There are a number of tickets remaining for the 0.3.0 release that have to get done first, but then I can spend some time on these tickets.

**Comment by nr0q** [comment]
Any updates on this enhancement? This would be great to allow SDRTrunk to also work to scan/stream conventional systems too!

**Comment by denis-d** [comment]
Hope you will implement it soon. We have many mixed systems here.

**Comment by smyers119** [comment]
Hi, I am interested in this as well.  Ideally ctcss/cdcss decoding would fall under a identifier in the alias section.  So it would give us a way to label the channel.  I would be interested in offering a bounty if that is an option

**Comment by smyers119** [comment]
@DSheirer In case you didn't catch it, I added a bounty on this.  Thanks for your hard work.

**Comment by DSheirer** [comment]
I think the latest power squelch is sufficient for squelching control.  However, to give more fine-grained control over how the decoded audio is handled, I'm going to add separate CDCSS and CTCSS decoders so that any audio generated from an NBFM squelch controlled channel can also be managed with Aliases where you can create aliases to control monitoring, recording and streaming of these calls.  

So, if you only want to hear audio from a repeater for specific squelching tones, you can control this with aliases, however the NBFM decoder will decode all audio that is transmitted on the repeater.

Closing this issue as not-implemented.
