### ISSUE TITLE
Alias list. 0.5.0a1

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#809]
In the "Playlist-> Channels" window you cannot exclude "List alias":

![Снимок экрана 2020-05-09 в 17 30 28](https://user-images.githubusercontent.com/58341369/81476630-8a487c80-921b-11ea-893f-f6902901d84e.png)

But in another window "Playlist-> Aliases" this can be done.

![Снимок экрана 2020-05-09 в 17 31 23](https://user-images.githubusercontent.com/58341369/81476634-92a0b780-921b-11ea-97fa-f1d7f486d7c9.png)

Pls also note the problem with the frequency reset:

**#781  During any actions in the "Playlist-> Channels" window, the frequency is erased to the value "zero".**

1. Perform editing in this window, for example, the line site. 
2. Then press the save button. 
As a result, the frequency is reset to zero.

 My frequency is now reset, and I can completely restore it only by downloading a backup of the playlist.

**Comment by DSheirer** [comment]
I updated the playlist editor to **force** users to select an alias list in channels because one of the biggest issues that users have is understanding that a channel requires an alias list in order to control audio recording, streaming, etc.

However, I understand that some uses will have aliases that do not have an alias list assigned, so I had to account for that (legacy) situation where some users may have aliases that do not have an alias list, in other words these aliases are now orphans because there is no way to see them by selecting an alias list.  So, I allow the 'No Alias List' in the alias editor, but I do not allow it in the Channel Editor.  This gives the user an opportunity to move those orphaned aliases to a valid alias list.

This is all designed to better 'help' the user to avoid situations where the application doesn't work the way that they think it should.

I'm working on #781.
