### ISSUE TITLE
Multiple instances of SDRtrunk

### ISSUE THREAD

**Issue by malchiuri** [DSheirer/sdrtrunk#882]
Hello,
I have 4 dongles in a USB hub. All have the same name: Tuner = R820T, ID = 00000001.
Is there a way to change ID?
SDRtrunk assign all of them to itself, and does not allow another instance of SDRtrunk or SDRsharp to access any of them.
Is there a way to bypass it?
Thank you.

**Comment by DSheirer** [comment]
You can post user support questions like this in the google groups email support group or in the Discord server.  Both are linked on the project home page.

Search google for changing the serial number on the RTL2832.  There's several approaches to do it.  I've heard that sdr-console has a built in capability and then there's a command line utility that's included in the rtl2832 library.

There's currently no way to blacklist a tuner in sdrtrunk so that it doesn't take all of the tuners for itself.
