### ISSUE TITLE
Duplicate Call Detection May Stop Working

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#905]
As reported in: https://groups.google.com/g/sdrtrunk/c/LqAF8XzWQrs

Duplicate detection may stop working after a period of time

Add try/catch block to the DuplicateCallDetector.process() method to trap any errors that may be thrown and could cause the detector thread to die.

**Comment by NoahWL** [comment]
I believe this is also related to the memory leak others have reported.  At least in the few crash dumps I've taken, the LinkedTransferQueue in SystemDuplicateCallDetector fills up the entire heap since process() is never called to empty it.  Still looking for what causes it to die in the first place.  Sometimes it runs out of memory within a few hours, sometimes it runs for days without any issue with no config changes.
