### ISSUE TITLE
Feature: ability to toggle FFT and spectral/waterfall display processing

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#96]
Add capability to suspend FFT processing and spectral/waterfall display.

Save user preference so that the setting persists across application sessions.

**Comment by nr0q** [comment]
I'd like request bumping this up to med, I'm having some success running sdrtunk on an ITX computer with a Celeron-M processor, but the jmbe decoder crashes because I'm out of resources taken up by the waterfall/spectral display. I believe if I could turn it off, it would run better on lower end computers.

**Comment by chudgoo** [comment]
Issue #92  is about a similar goal. Basically, running on very low end hardware.
Though people's intentions (including my own) were to run a streaming server, headless, without sound output. (easy enough... remove JMBE from the sdrtrunk dir)
