### ISSUE TITLE
Alias List / Group

### ISSUE THREAD

**Issue by rd0fun** [DSheirer/sdrtrunk#984]
I'm running on MacOS. I can't for the life of me figure out how to delete an Alias List or Create an Alias Group as documented in the user manual. 

I'm importing a P25 system from RadioReference, and I'd like to create the groups automatically based on tags. Such that the import, for example, uses the "Law Enforcement" tags to create an AliasGroup called "Law Enforcement" and that group is assigned to a specific Alias List named for the system.

Maybe I don't understand how this is intended to be used?

Any help would be appreciated.

**Comment by DSheirer** [comment]
When deleting an alias list, delete all of the aliases from the list and then remove the alias list name from any channels.  The next time you start the software, the alias list will be gone.

The group label for aliases provides no functionality.  It is simply meant to be used as a filter.

You can post user questions like these in the email support forum or on the discord support channel.  I'll close this issue since you're not reporting an issue with the software.

cheers,
Denny
